In [2]:
import numpy as np

In [4]:
arr_1d = np.array([1,2,3,4,5])
print(arr_1d)

[1 2 3 4 5]


In [5]:
arr_2d=np.array([[1,2,3],[4,5,6]])
print(arr_2d)

[[1 2 3]
 [4 5 6]]


List vs Numpy array

In [6]:
py_list=[1,2,3]
print("Python list multiplication ",py_list*2)

Python list multiplication  [1, 2, 3, 1, 2, 3]


In [ ]:
np_array=np.array([1,2,3]) #element wise multiplication
print(np_array*2)
import time
start=time.time()
py_list=[i*2 for i in range(1000000)]
print("\n List operation time: ",time.time()-start)

start=time.time()
np_array=np.arange(1000000)*2
print("\n Numpy operation time: ",time.time()-start)


[2 4 6]

 List operation time:  0.08773636817932129

 Numpy operation time:  0.01057887077331543


creating array from scratch

In [9]:
zeros=np.zeros((3,4))
print("zeros array: \n",zeros)

zeros array: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [10]:
ones=np.ones((2,3))
print("one array : \n",ones)

one array : 
 [[1. 1. 1.]
 [1. 1. 1.]]


In [11]:
full=np.full((2,2),7)
print("full array :\n",full)

full array :
 [[7 7]
 [7 7]]


In [12]:
random=np.random.random((2,3))
print("ramdom array: \n",random)

ramdom array: 
 [[0.81365743 0.05044338 0.81092071]
 [0.05828723 0.6293139  0.33744061]]


In [13]:
seq=np.arange(0,10,2)
print("sequence array : \n",seq)

sequence array : 
 [0 2 4 6 8]


Vector,Matrix,Tensor

In [5]:
vector=np.array([1,2,3])
print("Vector: ",vector)

matrix=np.array([[1,2,3],[4,5,6]])
print("Matrix :",matrix)

tensor=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print("Tenosr :",tensor)


Vector:  [1 2 3]
Matrix : [[1 2 3]
 [4 5 6]]
Tenosr : [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


Array Properties

In [6]:
arr=np.array([[1,2,3],[4,5,6]])
print("Shape ",arr.shape)
print("Dimension ",arr.ndim)
print("Size ",arr.size)
print("DType ",arr.dtype)

Shape  (2, 3)
Dimension  2
Size  6
DType  int64


Array Reshaping

In [7]:
arr=np.array(12)
print("Original Array ",arr)

Original Array  12
