In [4]:
import numpy as np

In [7]:
arr_1d = np.array([1,2,3,4,5])
print(arr_1d)

[1 2 3 4 5]


In [8]:
arr_2d=np.array([[1,2,3],[4,5,6]])
print(arr_2d)

[[1 2 3]
 [4 5 6]]


List vs Numpy array

In [9]:
py_list=[1,2,3]
print("Python list multiplication ",py_list*2)

Python list multiplication  [1, 2, 3, 1, 2, 3]


In [10]:
np_array=np.array([1,2,3])
print(np_array*2)


[2 4 6]
